# Generated by Django 5.1.5 on 2025-03-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('comprar_productos', 'puede comprar productos')]},
        ),
    ]
